on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  update-analytics:
    name: Update analytics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno --allow-env --allow-net --allow-read --allow-write get-analytics.ts
        env:
          WAI_SITE_ID: ${{ secrets.WAI_SITE_ID }}
          WAI_TOKEN: ${{ secrets.WAI_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update analytics data"
